---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  eslint:
    enabled: false
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- config/
- db/
- spec/
- test/
- vendor/
- app/assets/
- .idea/
