AllCops:
  Exclude:
    - db/**/**
    - config/**/**
Metrics/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Documentation:
  Enabled: false
